### ISSUE TITLE
Неправильное отображение SyntaxError

### ISSUE THREAD

**Issue by zeckson** [htmlacademy/console.js#9]
Дан код:
```
const agentName;

agentName = '008';

console.log('Имя агента: ' + agentName);
```

Должен получить в консоли следующее сообщение:
```
Uncaught SyntaxError: Missing initializer in const declaration
```

Вместо этого вижу:
```
Error: [object Object]
    at Object.F.a.error (https://htmlacademy.github.io/console.js/js/index-silent.js:1:13848)
    at https://htmlacademy.github.io/console.js/js/index-silent.js:1:14813
    at Array.forEach ()
    at https://htmlacademy.github.io/console.js/js/index-silent.js:1:14785
    at https://htmlacademy.github.io/console.js/js/index-silent.js:1:14960
    at b.value (https://up.htmlacademy.ru/static/demojs/main.min.16.js:13:11937)
    at b. (https://up.htmlacademy.ru/static/demojs/main.min.16.js:13:9180)
    at d.notifyAll (https://up.htmlacademy.ru/static/demojs/main.min.16.js:5:4201)
    at e.close (https://up.htmlacademy.ru/static/demojs/main.min.16.js:5:2734)
    at e.closeAll (https://up.htmlacademy.ru/static/demojs/main.min.16.js:5:6542)
```

**Comment by nikolayemrikh** [comment]
Fixed
